# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes: 
         - /home/adnan/Documents/Alturos Demo Project/us-counties.csv:/home/adnan/Documents/Alturos Demo Project/us-counties.csv

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
